#markdown: rdiscount
permalink: /:title/
url: http://qiaoketiqiu.com
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: 翘课踢球
description: 翘课踢球 | Stop talking, start doing.
author: qiaoketiqiu
email: nangongyinyu@163.com
about: "从复制开始，至原创终止"
